# Generated by Django 3.1.3 on 2020-12-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('author', models.FileField(blank=True, default='', upload_to='', verbose_name='Автор')),
            ],
        ),
    ]
