# Generated by Django 3.1.3 on 2020-12-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='video',
            name='watched_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Автор'),
        ),
    ]
