# Generated by Django 3.1 on 2021-03-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20201218_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(default=1, upload_to='images', verbose_name='Картика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=1, upload_to='videos', verbose_name='Видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='watched_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество просмотров'),
        ),
    ]
