# Generated by Django 3.1.4 on 2021-03-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210309_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='opisanie',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='video',
            name='watched_like',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество лайков'),
        ),
    ]
