# Generated by Django 3.1.4 on 2021-04-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=150, verbose_name='Описание'),
        ),
    ]
