# Generated by Django 3.1.4 on 2021-04-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20210402_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание'),
        ),
    ]
