# Generated by Django 3.1 on 2021-04-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20210406_1758'),
        ('videos', '0009_video_rating'),
    ]

    operations = [
    ]
