# Generated by Django 3.1 on 2021-03-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_analytics', '0002_auto_20210330_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchanalytics',
            old_name='session_key',
            new_name='sesId',
        ),
        migrations.RenameField(
            model_name='watchanalytics',
            old_name='video_id',
            new_name='videoId',
        ),
    ]
